# Generated by Django 4.1.7 on 2023-05-03 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMich',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'contact_mich',
                'managed': False,
            },
        ),
    ]
